docs/sevenpreneur-ddl.sql, docs/sevenpreneur-dml.sql, docs/sevenpreneur.dbml
Table users, tokens, and roles are used for user flow (register, login, logout) and user management (edit).
Enum type status_enum is introduced to be used for users table and other tables (for further development).
Enum type u_stage_enum and u_industry_enum are used for describing the users.
Related: SVP-8 SVP-9 SVP-10
=> [DB] Create users, tokens, and roles table

src/middleware.js
=> SVP-21-Infra-Create-Environment-Staging

src/app/(www)/www/layout.js
Add Tiktok Pixel Script on Layout www
=> Tiktok Pixel Script

src/app/components/templates/HeroEventRestart25.jsx, src/app/components/templates/SpeakersLineUpRestart25.jsx
+ Add Basuki Tjahja Purnama
+ Bhima Yudhistira
=> Add Speakers RE:START 25

example.env, prisma/schema.prisma, src/app/(admin)/admin/client-greeting.tsx, src/app/(admin)/admin/layout.tsx, src/app/(admin)/admin/page.tsx, src/app/(api)/api/trpc/[trpc]/route.ts, src/middleware.js, src/trpc/client.tsx, src/trpc/init.ts, src/trpc/routers/_app.ts
- **middleware:** Use simple substring for getting subdomain
- **tRPC:** Pass the tRPC base URL to the client
- **tRPC:** Check the `Origin` header to allow/block requests
- Code style fixes
New environment variables:
- `BASE_URL`: (local-only) base URL to be sent to the client
- `DOMAIN_MODE`: `local` (for local uses) or `staging` (in staging)
| Env. variable | Local | Staging | Production |
|:------------- |:-----:|:-------:|:----------:|
| `DOMAIN_MODE` | `local` | `staging` | `production` or _(empty)_ |
| `BASE_URL`    | `localhost:3000` | _(empty)_ | _(empty)_ |
Related: SVP-27
=> [Infra] Fix the tRPC's base URL and CORS

src/app/(admin)/admin/page.tsx, src/app/(admin)/admin/users/[user_id]/page.jsx, src/app/(admin)/admin/users/create/page.jsx, src/app/(admin)/admin/users/page.jsx, src/app/components/elements/AppButton.jsx, src/app/components/elements/DropdownMenuCMS.jsx, src/app/components/elements/InputCMS.jsx, src/app/components/elements/SelectCMS.jsx, src/app/components/elements/UserItemListCMS.jsx, src/app/components/templates/SidebarCMS.jsx
=> FE - Detail Page User

.gitignore, next.config.mjs, package-lock.json, package.json, src/app/(admin)/admin/client-greeting.tsx, src/app/(admin)/admin/page.tsx, src/app/(api)/api/auth/callback/google/route.ts, src/app/(api)/api/trpc/[trpc]/route.ts, src/app/components/templates/HeroEventRestart25.jsx, src/app/components/templates/SpeakersLineUpRestart25.jsx, src/trpc/routers/_app.ts, src/trpc/routers/auth.ts, src/trpc/routers/hello.ts, src/trpc/utils/google_oauth.ts, src/trpc/utils/validation.ts
=> FE - Update Speakers

src/app/components/templates/LoginContainer.jsx, src/middleware.js
+ Middleware to protect admin routes
+ Middleware to protect agora routes
+ Middleware to protect www routes
+ Remove env staging on middleware
+ Add loading state on Google Login button
=> Added middleware to protect routes

src/trpc/client.tsx, src/trpc/routers/_app.ts, src/trpc/routers/read.ts, src/trpc/utils/validation.ts
New endpoints:
- `read.industry`
- `read.entrepreneurStage`
- `read.role`
- `read.user`
New function: `setSessionToken()`
Related: SVP-38
=> [BE][FE] Add endpoints and auth header in tRPC

src/app/(admin)/admin/layout.tsx, src/app/(admin)/admin/users/page.jsx, src/app/components/elements/StatusLabelCMS.jsx, src/app/components/elements/UserBadgeCMS.tsx, src/app/components/elements/UserItemListCMS.jsx, src/app/components/elements/UserListCMS.tsx, src/app/components/templates/SidebarCMS.tsx, src/lib/actions.ts, src/middlewares/withAuth.js, src/trpc/routers/auth.ts
+ Fix middleware
+ Fix delete token when logout
+ Add data for user list
+ Add data for user badge CMS
=> update integrations for check sessions, middleware, & user list. 

src/app/(admin)/admin/users/create/page.jsx, src/app/(admin)/admin/users/page.jsx, src/app/components/elements/TextAreaCMS.tsx, src/app/components/elements/UserBadgeCMS.tsx, src/app/components/templates/UserCreateCMS.tsx, src/app/components/templates/UserListCMS.tsx, src/app/components/templates/UserProfileDetailCMS.tsx
+ Integrations enum data to form create
+ Integrations enum data to user detail profile
=> Integrations Enum Data

src/app/(admin)/admin/users/[user_id]/edit/page.jsx, src/app/(admin)/admin/users/[user_id]/page.jsx, src/app/(admin)/admin/users/create/page.jsx, src/app/(admin)/admin/users/page.jsx, src/app/components/elements/DropdownMenuCMS.jsx, src/app/components/elements/UserItemListCMS.jsx, src/app/components/templates/UserEditCMS.tsx, src/app/components/templates/UserListCMS.tsx, src/app/components/templates/UserProfileDetailCMS.tsx
+ Added edit user form
+ Fix dropdown issue user list
+ Fix user detail profile
=> Integrations Edit User Form

src/app/components/elements/AttributeLabelCMS.jsx, src/app/components/elements/StatusLabelCMS.tsx, src/app/components/elements/UserItemListCMS.tsx, src/app/components/templates/UserCreateCMS.tsx, src/app/components/templates/UserEditCMS.tsx, src/app/components/templates/UserListCMS.tsx, src/app/components/templates/UserProfileDetailCMS.tsx
+ Integrate delete with tRPC
+ Refactor UserItemList from jsx to tsx
+ Added redirect after execution create and edit
+ Fix problem date of birth
+ change case form lowercase to uppercase
=> Added function to delete user

src/app/(www)/www/auth/login/page.jsx, src/app/components/elements/AppButton.tsx, src/app/components/elements/AppDialogBox.tsx, src/app/components/elements/UserItemListCMS.tsx, src/app/components/templates/AppLoginContainer.jsx, src/app/globals.css
…ner, add color global cms
+ Added Alert Dialog Box
+ Added fonClasses variant di AppButton
+ Change filename: AppLoginContainer.jsx
+ Added semi desctructive color in globals.css
=> Alert-dialog-box

package-lock.json, package.json, src/app/components/elements/UploadAvatarUserCMS.tsx, src/app/components/templates/UserCreateCMS.tsx, src/app/components/templates/UserEditCMS.tsx, src/app/components/templates/UserProfileDetailCMS.tsx, src/lib/supabase.ts
+ Added upload image avatar, change image, and remove
+ Implement to Create User Form
+ Implement to Edit User Form
+ Bug in (Remove avatar in edit form then save) => failed null value
=> Added Upload Image

docs/db/sevenpreneur-ddl.sql, docs/db/sevenpreneur.dbml
New tables:
- `cohorts`
- `cohort_prices`
- `modules`
- `lessons`
- `materials`
- `projects`
Related: SVP-49 SVP-42 SVP-43 SVP-45 SVP-44 SVP-46 SVP-47
=> [DB] Add LMS-related tables

src/app/(admin)/admin/users/page.jsx, src/app/components/buttons/AppButton.tsx, src/app/components/forms/CreateCohortFormCMS.tsx, src/app/components/forms/CreateUserFormCMS.tsx, src/app/components/modals/AppSheet.tsx, src/app/components/stepper/PriceTierStepperCMS.tsx, src/app/components/templates/UserListCMS.tsx, src/app/globals.css
add new variant app button, refactor list user, rename button create
=> Added price form cohort, 

src/trpc/routers/auth.ts, src/trpc/routers/create.ts, src/trpc/routers/delete.ts, src/trpc/routers/list.ts, src/trpc/routers/read.ts, src/trpc/routers/update.ts, src/trpc/utils/slug.ts, src/trpc/utils/string_date.ts, src/trpc/utils/validation.ts
New helper functions:
- `createSlugFromTitle()`
- `stringIsTimestampTz()`
- `stringToDate()`
Also in this PR:
- Use `$executeRaw` only when using `CURRENT_TIMESTAMP`
Related: SVP-48 SVP-50 SVP-51 SVP-52
=> [BE] Add CRUD for cohorts table

src/trpc/routers/create.ts, src/trpc/routers/delete.ts, src/trpc/routers/list.ts, src/trpc/routers/read.ts, src/trpc/routers/update.ts
Related: SVP-79 SVP-80 SVP-81 SVP-82 SVP-83
Additional commits:
- Only include `cohort_prices` when reading from `cohorts`
=> [BE] Add CRUD for cohort_prices table

src/app/(admin)/admin/client-greeting.tsx, src/app/(admin)/admin/layout.tsx, src/app/(admin)/admin/page.tsx, src/app/(api)/api/trpc/[trpc]/route.ts, src/trpc/init.ts, src/trpc/routers/hello.ts, src/trpc/server.tsx
=> [Infra] Add server-side tRPC calls with auth

src/app/(admin)/admin/cohorts/[cohort_id]/learnings/[learning_id]/page.tsx, src/app/(admin)/admin/cohorts/[cohort_id]/page.tsx, src/app/(admin)/admin/cohorts/page.tsx, src/app/(admin)/admin/layout.tsx, src/app/(admin)/admin/page.tsx, src/app/(admin)/admin/users/[user_id]/edit/page.tsx, src/app/(admin)/admin/users/[user_id]/page.tsx, src/app/(admin)/admin/users/create/page.tsx, src/app/(admin)/admin/users/page.tsx, src/app/(agora)/agora/layout.js, src/app/(www)/www/layout.tsx, src/app/components/navigations/SidebarCMS.tsx, src/app/components/state/404NotFound.tsx, src/app/components/state/DisallowedMobile.tsx, src/app/layout.tsx, src/app/not-found.tsx
+ refactor layout
+ add not-found.tsx
=> [FE] State 404 & State Disallowed Mobile

src/app/components/indexes/EnrolledUserListCMS.tsx, src/app/components/indexes/LearningListCMS.tsx, src/app/components/indexes/ModuleListCMS.tsx, src/app/components/indexes/ProjectListCMS.tsx, src/app/components/items/LearningSessionItemCMS.tsx, src/app/components/labels/LearningSessionIconLabelCMS.tsx, src/app/components/templates/CohortDetailsCMS.tsx
added list component: 
- module, 
- project, 
- enrolled user
=> [FE] Integrate learning list,

src/app/components/indexes/LearningListCMS.tsx, src/app/components/items/LearningSessionItemCMS.tsx, src/app/components/navigations/AppBreadcrumbItem.tsx, src/app/components/templates/CohortDetailsCMS.tsx
=> SVP-99: [FE] Integrate delete learning

src/trpc/routers/create.ts, src/trpc/routers/delete.ts, src/trpc/routers/list.ts, src/trpc/routers/read.ts, src/trpc/routers/update.ts
Related: SVP-65 SVP-66 SVP-67 SVP-68 SVP-69
=> [BE] Add CRUD for materials table

src/trpc/routers/create.ts, src/trpc/routers/delete.ts, src/trpc/routers/list.ts, src/trpc/routers/read.ts, src/trpc/routers/update.ts
Related: SVP-61 SVP-62 SVP-64 SVP-100 SVP-101
=> [BE] Add CRUD for modules table

src/app/components/forms/EditLearningFormCMS.tsx, src/app/components/forms/UpdateVideoRecordingForm.tsx, src/app/components/items/FileItemCMS.tsx, src/app/components/items/LocationItemCMS.tsx, src/app/components/items/MeetingPlatformItemCMS.tsx, src/app/components/templates/LearningDetailsCMS.tsx, src/lib/extract-youtube-id.ts
Finalize Learning Details Page. Related: SVP-98 SVP-97 SVP-71
=> [FE] Added Edit Learning Form, Update Video Recording, 

src/app/components/forms/CreateMaterialFormCMS.tsx, src/app/components/forms/EditMaterialFormCMS.tsx, src/app/components/indexes/MaterialListCMS.tsx, src/app/components/items/FileItemCMS.tsx
Related: SVP-116 SVP-72 SVP-117
=> [FE] Add Create Material, Update Material, Delete Material. 

docs/db/sevenpreneur-ddl.sql, docs/db/sevenpreneur-dml.sql, docs/db/sevenpreneur.dbml, prisma/schema.prisma, src/trpc/routers/README.md, src/trpc/routers/list.ts
New table: `payment_channels`
New endpoint: `list.payment_channels`
Also in this PR:
- Update role-access documentation for the routes
Related: SVP-141 SVP-142
=> [DB][BE] Add payment channels

docs/db/sevenpreneur-ddl.sql, docs/db/sevenpreneur-dml.sql, docs/db/sevenpreneur.dbml, prisma/schema.prisma, src/lib/price_calc.ts, src/trpc/routers/list.ts
New columns:
- `status`
- `calc_vat`
List of payment channels is updated.
Also in this PR,
- Return all columns and only active rows for `payment_channels` table
- Add final price calculation helper function: `calculateFinalPrice()`
Related: SVP-143
=> [DB] More columns for payment_channels table

prisma/schema.prisma, src/app/(api)/api/xendit/webhook/route.ts, src/trpc/routers/README.md, src/trpc/routers/_app.ts, src/trpc/routers/purchase.ts
The `users_cohorts` table is defined explicitly as many-to-many relationship in the Prisma schema.
This was added in a59762d36dc1bb8834c3125b479966e51fd8bf6c.
Also in this PR,
- Rename `buy` -> `purchase`
Related: SVP-150
=> [BE] Fix adding the paid cohort to the paying user

src/trpc/routers/list.ts, src/trpc/routers/purchase.ts
The Map class is used instead.
=> [BE] Rename to cohort_price_name in list.transactions

src/lib/xendit.ts, src/trpc/routers/purchase.ts
New endpoint: `purchase.cancel`
Rename: `XenditCreateInvoiceResponse` -> `XenditInvoiceResponse`
Related: SVP-155
=> [BE] Add purchase.cancel endpoint

docs/db/sevenpreneur-ddl.sql, docs/db/sevenpreneur.dbml, prisma/schema.prisma, src/trpc/routers/README.md, src/trpc/routers/create.ts, src/trpc/routers/delete.ts, src/trpc/routers/list.ts, src/trpc/routers/read.ts, src/trpc/routers/update.ts
Related: SVP-166 SVP-158 SVP-160 SVP-162 SVP-159 SVP-161
=> [DB][BE] Add project submissions

docs/db/sevenpreneur-ddl.sql, docs/db/sevenpreneur.dbml, prisma/schema.prisma, src/trpc/routers/README.md, src/trpc/routers/create.ts, src/trpc/routers/delete.ts, src/trpc/routers/list.ts, src/trpc/routers/read.ts, src/trpc/routers/update.ts
New tables:
- `playlists`
- `videos`
- `users_playlists`
- `educators_playlists`
New endpoints:
- `create.playlist`
- `list.playlists`
- `read.playlist`
- `update.playlist`
- `delete.playlist`
- `create.educatorPlaylist`
- `list.educatorsPlaylist`
- `delete.educatorPlaylist`
Related: SVP-168 SVP-169 SVP-171
=> [DB][BE] Add VOD-related tables and endpoints

src/app/(www)/www/playlists/[playlist_name]/[playlist_id]/checkout/page.tsx, src/app/(www)/www/playlists/[playlist_name]/[playlist_id]/page.tsx, src/app/(www)/www/transactions/[transaction_id]/page.tsx, src/app/(www)/www/transactions/page.tsx, src/app/components/forms/CheckoutPlaylistFormSVP.tsx, src/app/components/indexes/VideoCoursePlaylistSVP.tsx, src/app/components/items/VideoCourseItemSVP.tsx, src/app/components/pages/PlaylistDetailsSVP.tsx, src/app/components/pages/TransactionStatusDetailsSVP.tsx, src/app/components/templates/OfferHighlightVideoCourseSVP.tsx, src/lib/actions.ts, src/lib/duration-from-seconds.ts, src/lib/rounded-hour-from-second.ts
- Make public playlist detail page,
- Integrate video duration, total_episodes, and total duration
=> [FE]  Integrate payment playlist

src/app/components/buttons/AvatarBadgeSVP.tsx, src/app/components/buttons/ThemeSwitcher.tsx, src/app/components/elements/AppDropdown.tsx, src/app/components/elements/AppDropdownItemList.tsx, src/app/components/items/VideoCourseItemSVP.tsx, src/app/components/navigations/HeaderNavbarSVP.tsx, src/app/components/pages/PlaylistDetailsSVP.tsx, src/app/components/templates/OfferHighlightVideoCourseSVP.tsx, src/app/components/titles/SectionTitleSVP.tsx, src/app/layout.tsx
=> [FE] Add Theme Switcher, Refactor Darkmode on Playlist Details and

src/trpc/routers/README.md, src/trpc/routers/create.ts, src/trpc/routers/delete.ts, src/trpc/routers/update.ts
=> [BE] Add CRUD for videos table

docs/db/sevenpreneur-ddl.sql, docs/db/sevenpreneur.dbml, prisma/schema.prisma
=> [DB] Add discounts table

src/trpc/routers/read.ts
New properties:
- `user_email`
- `user_phone_country`
- `user_phone_number`
- `user_avatar`
Related: SVP-189
=> [BE] Add user_* in read.transaction

docs/db/sevenpreneur-ddl.sql, docs/db/sevenpreneur.dbml, prisma/schema.prisma
- A unique constraint is added to `discounts` table. SVP-207
- `discount_id` and `discount_amount` is added to `transactions` table. SVP-208
=> [DB] Discount-related changes

src/trpc/routers/README.md, src/trpc/routers/list.ts, src/trpc/routers/read.ts
=> [BE] Limit access scopes to some endpoints

src/app/components/items/FAQItemBlueprintProgramSVP.tsx, src/app/components/items/LearningSessionItemBlueprintProgramSVP.tsx, src/app/components/labels/PackageLabelBlueprintProgramSVP.tsx, src/app/components/pages/BlueprintProgramSVP.tsx, src/app/components/templates/CuriculumSessionsBlueprintProgramSVP.tsx, src/app/components/templates/FAQCustomerBlueprintProgramSVP.tsx, src/app/components/templates/HeroBlueprintProgramSVP.tsx, src/app/components/templates/PackagePlansBlueprintProgramSVP.tsx
Added size for label package, Update speaker information
=> [FE] Create FAQ, Add label on Learning Session, 

src/app/components/forms/CheckoutEventFormSVP.tsx, src/app/components/forms/CreateDiscountFormCMS.tsx, src/app/components/forms/CreateInvoiceFormCMS.tsx, src/app/components/forms/EditDiscountFormCMS.tsx, src/app/components/modals/ApplyDiscountModalSVP.tsx, src/lib/actions.ts, src/trpc/routers/purchase.ts
Update form create discount and edit discount
Activate check discount for event in CMS
Create actions ts check discount
Update endpoint checkDiscount
=> [Fullstack] Activate Promo Discount on Checkout Page Customer,
